language: android

android:
  components:
  - tools
  - platform-tools

jdk:
- oraclejdk8

# as per http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false

before_install:
# Install SDK license so Android Gradle plugin can install deps.
- mkdir "$ANDROID_HOME/licenses" || true
- echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"

# script for build and release via Travis to Bintray
script:
  - ./buildViaTravis.sh

# cache between builds
cache:
  directories:
  - $HOME/.gradle

env:
  global:
  - secure: "nn9MsbQaN1wfp0wpJo1MHjF5SGPmSx1QP+6horvLH/yD1Y8NAXjZDU1wo+QSIeowYWowXs+NOkTPxBrxpBqZvbop+2/JqGP5JKhBAcibDHM3aAT1ULcs/XPt1R+MlpI5M5DurcdRizMJIWEFDsH6ZLhI1I1WKSEW5/qf45XD/S5s7u8qLrNiEJUSwqVZqry2tGpeo4s2jPSQdW2GmlNhgUMeIb33KqMK27N2tlLMHAx+xae2jAwYW3L/aL++0R6Gu/LFgkxEderpmC2ejp7x+h3Nfk0ja/hN/D0IUAK/FBpa1LE9QYdVSLXbkobbrGwRB+JKuWKLVku4mcQchMw8xIAnAXtItrBAtLlxeAk/SRzELUOKc/+VHuqWgNgmPgXarORNrkmMPtHXvpI+fgKWi0Nb7Ffh8aO/BhUvTTP83ZGvJVutqC4ljazHE7YV964+go2yHjGuyFhGX8qohbtZeqXWpr7YmX2eJiSFI00/mtOqmZJq9Nd0Y28OfGwHu9oX6eFQq2dzn3qeIGBbebp0kwVecykb8wuDgAKln5fWRfF2Z5yDXPEPqDtRGU5z8F8yWr6h6HniAWc1RgOIyHNDWfLCWg2ZKPJ/4sL/mwAUQcxKimWmU6NcYI3DY0n8OtzyuxPKdHky5w22a8BMPh4AgHOmHIhfza+Y2XQHWoRDAm8="
  - secure: "GUJ91uRhv89AJcpFqjDrDeuWPCxoKaNNr/tqspf1VQXjHBJ+1Qp6lEm+kgDxxxVX03yonWdQZ0snO5q7Sl9Mi3yfVEoBLEmSGhyfnvBfkSyIpPg5XYz6ADqCPzeE9fecP28T93OI3OG2LCXVSSiP923pCupO0Gy+jy5iTpFBbdnaSAFzQqrWDxCY+U55P1l2gV9FkMyyrOE515lIDqWe+q4p6cf0k6x8EZeuqHSDDIv8E7zdEnvOAVZk+nVsM7myKH+Tsw5y66cDwsX5r/S0BIiWANXE3XupXthsXF5zi0LH+4DAHtfVE3OkyhAkP3/P4LCy+/nLpyDKvwcWALIvBzjBH7acQQYcvRH2oXxhS9PiIaM6nE4phpsOcuy6QRwJY7CVe8IKGWtaU3D4tJSVMpebJfQf66xxhj+Q+mHsZ4izSH8wCaF+Ce5ZNkKyiUq01GKvC4bO3R7UMu4uHjtHcpaj3a15XZ1tYlozoHdZ+PXz83tIUfJt1jaXrnrM4f7hlPSf/GK7PfRoEnZJh+819uEf+vEhaLJUsQeQGMpE4KznaYEn9400B53+Ez/F0xzoQaRBtHASFv94Ja0jW6mdWxQ7HZjDMWPRA8rPTlsGR0xomK+jbBk2c/XAkN9m1bdvlYSVLgsFMvUrzBIWTsdGzZj/CWoYkjhUTk/uzYuTNeQ="